name: flashchat_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^4.1.1
  firebase_core: ^1.0.3
  firebase_auth: ^1.1.0
  cloud_firestore: ^1.0.5
  modal_progress_hud: ^0.1.3
  rflutter_alert: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
